### ISSUE TITLE
Did this ever merge into the foosel/Master? Still in development?

### ISSUE THREAD

**Issue by Booli** [daprice/OctoPrint#2]
Im looking for something just like this, but the foosel branch is a lot further(with cura integration etc.) which im also using. 

Can this be merged still? Or can I just copy the jinja2/css files or something?

**Comment by daprice** [comment]
I haven't updated this in a while because it was getting to be too much work to make OctoPrint's new features work well with it as they were added, and some things (e.g. the hover dialogs with print info) were never going to work well on a touchscreen without completely redesigning them.

You might be better off with [AstroPrint](https://github.com/3DaGoGo/AstroBox) which looks to be based on a more recent version of OctoPrint and was completely redesigned for touchscreen use.
